version: "3.8"

services:
  mongo:
    image: mongo
    volumes:
      - mongo-scrape-data:/data/db
    ports:
      - "6666:27017"
    env_file:
      - ./env/.database.env
    logging:
      driver: none
  flask:
    build: ./backend
    env_file:
      - ./env/.backend.env
    volumes:
      - ./backend/app:/app
    depends_on:
      - mongo
    ports:
      - "5000:5000"
  next:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    environment:
      SERVER: http://flask:5000/
    depends_on:
      - flask

volumes:
  mongo-scrape-data:
