version: "3.8"
services:
  db:
    image: mongo
    volumes:
      - mongo-scrape-data:/data/db
  app:
    build: .
    env_file:
      - ./env/.backend.env
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  mongo-scrape-data:
